services:
  mariadb-dev:
    image: mariadb:latest
    container_name: mariadb-dev
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      mariadb_net:
        ipv4_address: 172.31.0.2

volumes:
  mariadb_data:

networks:
  mariadb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
